stages:
- stage: BuildStage
  displayName: Build
  jobs:
  - job: BuildJob
    displayName: Build
    steps:
      # We emulate project build with file copying.
    - task: PowerShell@2
      displayName: Build Project
      inputs:
        targetType: filePath
        filePath: copy-file.ps1
        arguments: '"${{ parameters.appId }}/version.txt" "${{ parameters.appId }}-version.txt"'

    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Artifact
      inputs:
        targetPath: '${{ parameters.appId }}-version.txt'
        artifact: project-binaries

    - script: |
       # This variable is available within current job, but could not be accessed by other jobs or stages.
       echo "##vso[task.setvariable variable=TestVariable1;isOutput=false]Test Value 1"
       # This variable is not available within current job, but could be accessed by other jobs or stages.
       echo "##vso[task.setvariable variable=TestVariable2;isOutput=true]Test Value 2"
      name: SetOutputVariables
      displayName: Set Variables

    - script: |
       # This script will echo:
       # TestVariable1 = 'Test Value 1'
       # TestVariable2 = ''
       echo "TestVariable1 = '$(TestVariable1)'"
       echo "TestVariable2 = '$(TestVariable2)'"
      displayName: Print Variables

- template: deploy-stage-template.yaml
  parameters:
    appId: ${{ parameters.appId }}
    envName: test
    envDisplayName: Test

- template: deploy-stage-template.yaml
  parameters:
    appId: ${{ parameters.appId }}
    envName: prod
    envDisplayName: Production
