stages:
- stage: BuildStage
  displayName: Build
  jobs:
  - job: BuildJob
    displayName: Build
    steps:
      # We emulate project build with file copying.
    - task: PowerShell@2
      displayName: Build Project
      inputs:
        targetType: filePath
        filePath: copy-file.ps1
        arguments: '"${{ parameters.appId }}/version.txt" "${{ parameters.appId }}-version.txt"'

    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Artifact
      inputs:
        targetPath: '${{ parameters.appId }}-version.txt'
        artifact: project-binaries

- template: deploy-stage-template.yaml
  parameters:
    appId: ${{ parameters.appId }}
    envName: test
    envDisplayName: Test

- template: deploy-stage-template.yaml
  parameters:
    appId: ${{ parameters.appId }}
    envName: prod
    envDisplayName: Production
