trigger: none

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

variables:
  aws.region: us-east-1

stages:
- template: deploy-stage-template.yaml
  parameters:
    envName: test
    envDisplayName: Test
    isCDPipeline: true
