trigger:
  - master

pool:
  name: Azure Pipelines
  vmImage: ubuntu-latest

variables:
  aws.region: us-east-1

stages:
- template: ../pipeline-template.yaml
  parameters:
    appId: app1
